apiVersion1: 1 

datasources:
  - name: DS_PROMETHEUS 
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
  - name: DS_PROMETHEUS_PC
    type: prometheus
    access: proxy
    url: http://localhost:9100
    isDefault: false
