volumes:
  prometheus_data:
  grafana_data:

services:
  create-qbft:
    image: hyperledger/besu:latest
    container_name: create-qbft-${NUM_DIR}
    command: ["--data-path=data/Node-${NUM_DIR}",
              "--genesis-file=config/genesis.json",
              "--rpc-http-enabled",
              "--rpc-http-api=ETH,NET,QBFT,ADMIN",
              "--host-allowlist=\"*\"",
              "--rpc-http-cors-origins=\"all\"",
              "--rpc-http-port=${RPC_PORT}",
              "--rpc-http-host=0.0.0.0",
              "--p2p-port=${P2P_PORT}",
              "--metrics-enabled=true",
              "--metrics-port=${METRIC_PORT}",
              "--metrics-host=0.0.0.0",
              "--profile=ENTERPRISE"]

    volumes:
      - ./config:/opt/besu/config
      - ./data-node:/opt/besu/data
    
    ports:
      - ${RPC_PORT}:${RPC_PORT}
      - ${P2P_PORT}:${P2P_PORT}
      - ${METRIC_PORT}:${METRIC_PORT}
    network_mode: "host" 
    environment:
      - BESU_P2P_HOST=${IP_EXTERNE}   

  join-node:
    image: hyperledger/besu:latest
    container_name: join-node-${NUM_DIR}
    command: ["--data-path=data/Node-${NUM_DIR}",
              "--genesis-file=config/genesis.json",
              "--bootnodes=\"${ENODE_URL}\"",
              "--rpc-http-enabled",
              "--rpc-http-api=ETH,NET,QBFT,ADMIN",
              "--host-allowlist=\"*\"",
              "--rpc-http-cors-origins=\"all\"",
              "--rpc-http-port=${RPC_PORT}",
              "--rpc-http-host=0.0.0.0",
              "--p2p-port=${P2P_PORT}",
              "--metrics-enabled=true",
              "--metrics-port=${METRIC_PORT}",
              "--metrics-host=0.0.0.0",
              "--profile=ENTERPRISE"]

    volumes:
      - ./config:/opt/besu/config
      - ./data-node:/opt/besu/data
    
    ports:
      - ${RPC_PORT}:${RPC_PORT}
      - ${P2P_PORT}:${P2P_PORT}
      - ${METRIC_PORT}:${METRIC_PORT}
    network_mode: "host" 
    environment:
      - BESU_P2P_HOST=${IP_EXTERNE}
      
  start-node:
    image: hyperledger/besu:latest
    container_name: start-node-${NUM_DIR}
    command: ["--data-path=data/Node-${NUM_DIR}",
              "--genesis-file=config/genesis.json",
              "--bootnodes=\"${ENODE_URL}\"",
              "--rpc-http-enabled",
              "--rpc-http-api=ETH,NET,QBFT,ADMIN",
              "--host-allowlist=\"*\"",
              "--rpc-http-cors-origins=\"all\"",
              "--rpc-http-port=${RPC_PORT}",
              "--rpc-http-host=0.0.0.0",
              "--p2p-port=${P2P_PORT}",
              "--metrics-enabled=true",
              "--metrics-port=${METRIC_PORT}",
              "--metrics-host=0.0.0.0",
              "--profile=ENTERPRISE"]

    volumes:
      - ./config:/opt/besu/config
      - ./data-node:/opt/besu/data
    
    ports:
      - ${RPC_PORT}:${RPC_PORT}
      - ${P2P_PORT}:${P2P_PORT}
      - ${METRIC_PORT}:${METRIC_PORT}
    network_mode: "host" 
    environment:
      - BESU_P2P_HOST=${IP_EXTERNE}   

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: "host"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - ${PROM_PORT}:${PROM_PORT}

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: "host"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/dashboards
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana_data:/var/lib/grafana
    ports:
      - ${GRAF_PORT}:${GRAF_PORT}

  nginx:
    image: nginx:latest
    container_name: nginx-besu-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl/private:ro  # Ton certificat SSL ici
    ports:
      - "443:443"  # HTTPS
    network_mode: "host"
    depends_on:
      - create-qbft
      - join-node
      - start-node
